# Two containers:
# 1) backend – Flask/Gunicorn API on port 8000 (web search, AI chat, uploads)
# 2) frontend – Nginx serving static files on port 5500

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: examai-backend

    # Load secrets from .env (OPENAI_API_KEY, SERPER_API_KEY, etc.)
    env_file:
      - .env

    environment:
      - PORT=8000
      - RUNNER_BASE_URL=http://runner:7000
      - PYTHON_RUNNER_STRICT=true

    ports:
      - "8000:8000"
    volumes:
      # Persist uploaded files so /files/* links survive restarts
      - ./uploads:/app/uploads

    # Healthcheck without curl (use Python available in the image)
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/key-status').getcode()==200 else 1)"]
      interval: 20s
      timeout: 5s
      retries: 5

    networks:
      - examai-net
    restart: unless-stopped

  frontend:
    image: nginx:1.27-alpine
    container_name: examai-frontend

    volumes:
      - ./Frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./favicon.ico:/opt/icons/favicon.ico:ro
      - ./favicon.svg:/opt/icons/favicon.svg:ro

    ports:
      - "5500:80"

    depends_on:
      - backend

    networks:
      - examai-net
    restart: unless-stopped

  runner:
    build:
      context: ./runner
      dockerfile: Dockerfile
    container_name: examai-runner
    environment:
      - PORT=7000
    # Optional: expose for local testing; backend talks over the internal network name 'runner'
    ports:
      - "7000:7000"
    # Harden the sandbox container
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:7000/health').getcode()==200 else 1)"]
      interval: 20s
      timeout: 5s
      retries: 5
    read_only: true
    tmpfs:
      - /tmp:size=64m,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # Limit resources per-container (compose v2 classic keys; optional)
    pids_limit: 256
    # The following keys may be supported depending on your Docker/Compose version:
    # mem_limit: 512m
    # cpus: 0.50
    networks:
      - examai-net
    restart: unless-stopped

networks:
  examai-net:
    driver: bridge
