name: CI

on:
  push:
    branches:
      - main
      - 'refactor/**'
  pull_request:
    branches:
      - main

permissions: read-all

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
      - name: Run Python unit tests
        run: |
          cd backend && python -m pytest ../tests/unit/test_app.py -v

  solid-compliance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'tests/config/package.json'
      - name: Install dependencies
        run: |
          cd tests/config && npm install
      - name: Install Playwright browsers
        run: |
          cd tests/config && npx playwright install chromium
      - name: Run SOLID Compliance Tests
        run: |
          cd tests/config && npx playwright test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: solid-test-results
          path: tests/test-results/

  frontend-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'tests/config/package.json'
      - name: Install dependencies
        run: |
          cd tests/config && npm install
      - name: Lint JavaScript files
        run: |
          cd tests/config && npx eslint ../../frontend/js/**/*.js --config=eslint.config.js
